"""
scripts/make_report.py — Generate results/REPORT.md from the recorded experiment files.

Every number in the report is read from ``results/`` (window_results.csv,
paired_comparisons.csv, hmm_validation.csv, run_config.json); nothing is typed by hand.

Usage:
    python scripts/make_report.py [--results-dir results]
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import pandas as pd


def md(df: pd.DataFrame, floatfmt: str = "{:.2f}") -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            cells.append(floatfmt.format(v) if isinstance(v, (float, np.floating)) and pd.notna(v) else ("" if pd.isna(v) else str(v)))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def reading(row) -> str:
    if pd.isna(row["ci_low"]) or pd.isna(row["ci_high"]):
        return ""
    if row["ci_high"] < 0:
        return "cheaper"
    if row["ci_low"] > 0:
        return "costlier"
    return "no clear difference"


def comparison_table(comp: pd.DataFrame, rq: str, scope: str) -> pd.DataFrame:
    w = comp[(comp.level == "window") & (comp.rq == rq) & (comp.scope == scope)].copy()
    s = comp[(comp.level == "seed") & (comp.rq == rq) & (comp.scope == scope)].set_index(["treatment", "control"])
    rows = []
    for _, r in w.iterrows():
        sr = s.loc[(r.treatment, r.control)] if (r.treatment, r.control) in s.index else None
        rows.append({
            "Comparison": f"{r.treatment} vs {r.control}",
            "Δ IS (bps)": r["mean"],
            "95% CI": f"[{r.ci_low:+.2f}, {r.ci_high:+.2f}]",
            "p (Wilcoxon)": f"{r.p_value:.3f}" if pd.notna(r.p_value) else "",
            "Windows better": f"{100 * r.win_rate:.0f}%",
            "Seeds better": f"{int(sr.seeds_favouring)}/{int(sr.n_seeds)}" if sr is not None else "",
            "Reading": reading(r),
        })
    return pd.DataFrame(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", default="results")
    args = ap.parse_args()
    d = args.results_dir

    cfg = json.load(open(os.path.join(d, "run_config.json")))
    win = pd.read_csv(os.path.join(d, "window_results.csv"))
    comp = pd.read_csv(os.path.join(d, "paired_comparisons.csv"))
    hmm = pd.read_csv(os.path.join(d, "hmm_validation.csv"))

    lines = ["# KAIRO experiment report (generated by scripts/make_report.py)", ""]
    n_windows = win.groupby(["scenario", "seed", "strategy"]).size().iloc[0]
    lines += [
        "## Configuration", "",
        f"* Scenarios: {', '.join(cfg['scenarios'])}",
        f"* Seeds ({len(cfg['seeds'])}): {cfg['seeds']}",
        f"* Training steps per learned model: {cfg['train_timesteps']:,}",
        f"* Series length: {cfg['n_bars']} bars; horizon {cfg['horizon_steps']} bars; "
        + (f"order = {100 * cfg['order_participation']:.1f}% of the window's expected volume ({cfg['side']})"
           if cfg.get('order_participation') else f"order {int(cfg['target_inventory']):,} shares ({cfg['side']})"),
        f"* Test windows per (scenario, seed): {n_windows}; total paired windows: {n_windows * len(cfg['seeds']) * len(cfg['scenarios'])}",
        "",
        "Δ IS = treatment − control in implementation-shortfall bps (negative = treatment cheaper). "
        "'Seeds better' counts seeds whose mean paired difference is negative.",
        "",
    ]

    # Strategy means with fill rate
    means = (win.groupby("strategy")
             .agg(IS_bps=("implementation_shortfall_bps", "mean"),
                  fill_rate=("fill_rate", "mean"),
                  cost_usd=("total_execution_cost", "mean"))
             .reset_index().sort_values("IS_bps"))
    means["fill_rate"] = (means["fill_rate"] * 100).round(1)
    lines += ["## Mean shortfall by strategy (all scenarios, seeds and windows)", "",
              md(means.rename(columns={"strategy": "Strategy", "IS_bps": "IS (bps)", "fill_rate": "Fill %", "cost_usd": "Cost ($)"})), ""]

    piv = win.pivot_table(index="strategy", columns="scenario", values="implementation_shortfall_bps").reset_index()
    lines += ["## Mean shortfall by scenario (bps)", "", md(piv.rename(columns={"strategy": "Strategy"})), ""]

    lines += ["## RQ1: learned policies vs baselines (all scenarios)", "", md(comparison_table(comp, "RQ1", "ALL")), ""]
    lines += ["## RQ2: regime-aware vs the same agent without regime features", ""]
    for scope, title in [("ALL", "All scenarios"), ("TURBULENT", "Turbulent scenarios (regime_transition, stress, high_volatility, liquidity_shock)")]:
        lines += [f"**{title}**", "", md(comparison_table(comp, "RQ2", scope)), ""]
    lines += ["**By scenario**", ""]
    for scen in cfg["scenarios"]:
        t = comparison_table(comp, "RQ2", scen)
        t.insert(0, "Scenario", scen)
        lines += [md(t), ""]
    lines += ["## RQ3 control: regime-aware vs shuffled-regime control (all scenarios)", "",
              md(comparison_table(comp, "RQ3-control", "ALL")), "",
              "**Turbulent scenarios**", "", md(comparison_table(comp, "RQ3-control", "TURBULENT")), ""]

    # RQ4: consistency across algorithms
    r2 = comp[(comp.level == "window") & (comp.rq == "RQ2") & (comp.scope == "ALL")]
    lines += ["## RQ4: does the regime-aware effect appear for both algorithm classes?", ""]
    for _, r in r2.iterrows():
        lines.append(f"* {r.treatment} vs {r.control}: Δ = {r['mean']:+.2f} bps, 95% CI [{r.ci_low:+.2f}, {r.ci_high:+.2f}] → {reading(r)}")
    lines.append("")

    lines += ["## Regime detection quality (causal HMM vs the true latent regime, test region)", "",
              f"* Runs: {len(hmm)}; mean adjusted Rand index {hmm['test_ari'].mean():.3f} (min {hmm['test_ari'].min():.3f}, max {hmm['test_ari'].max():.3f})",
              f"* Mean accuracy {100 * hmm['test_accuracy'].mean():.1f}%", ""]
    out = os.path.join(d, "REPORT.md")
    open(out, "w", encoding="utf-8").write("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
